template = "https://github.com/giellalt/template-lang-und"
rev_id = 314
template_sha = "ad51f89a72714ab21c4272c003b7692c820e2b18"

[replacements]
__GLOTTOLOG_ID__ = "teni1238"
__LICENSE__ = "LGPLv3"
__REPO__ = "lang-tqn"
__UND2C__ = "tqn"
__UNDEFINED__ = "Sahaptin Tenino"
__UND__ = "tqn"
