template = "https://github.com/giellalt/template-lang-und"
rev_id = 282
template_sha = "23955e3e9b21e157f14f5b6fe8e1b45c170e2f29"

[replacements]
__GLOTTOLOG_ID__ = "teni1238"
__LICENSE__ = "LGPLv3"
__REPO__ = "lang-tqn"
__UND2C__ = "tqn"
__UNDEFINED__ = "Sahaptin Tenino"
__UND__ = "tqn"
