template = "https://github.com/giellalt/template-lang-und"
rev_id = 345
template_sha = "f04ff6c72fd325cdfed0bbaee815bd2f43d847a7"

[replacements]
__GLOTTOLOG_ID__ = "teni1238"
__LICENSE__ = "LGPLv3"
__REPO__ = "lang-tqn"
__UND2C__ = "tqn"
__UNDEFINED__ = "Sahaptin Tenino"
__UND__ = "tqn"
