theme: jekyll-theme-minimal
title: Sahaptin Tenino NLP Grammar
description: Finite state and Constraint Grammar based analysers, proofing tools and other resources
plugins:
  - jemoji

markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
